### PR TITLE
Curios support

### PR DESCRIPTION
**Pull request by MelanX**
I cleaned up the code a bit, updated Forge and other stuff, added a few things which are default.
I added support for Curios as a ring. Maybe I'll change it to charm.

TODO:
Equip Angel Ring with rightclick.

### CODE REVIEW

**Comment by DenisMasterHerobrine** [comment]
Hello, huge thanks for contributing for my project, since I have not so much time to continue modding atm, so I'll take a look into this PR asap and back to modding to get things to work as intended.

**Comment by MelanX** [comment]
Take your time, it's not ready enough :) I need to try things out for the right clock equipping 
Should have marked this as draft PR :D

**Comment by DenisMasterHerobrine** [comment]
> Take your time, it's not ready enough :) I need to try things out for the right clock equipping
> Should have marked this as draft PR :D

Implement ICurio to ItemRing and add canRightClickEquip() method returning "true". Also canEquip and playEquipSound methods can be implemented to ItemRing to add equip sound and boolean output to canEquip for Curios. Also - thing to be noticed, you removed a ItemRing class declaration, which throws a syntax error.

**Comment by MelanX** [comment]
Yes, I thought that, too.. but it doesn't work that easy.. :D 
Yes, it's just in this commit.. because I pushed it when I had a few other changes, too but don't wanted to push this. I removed this line to be pushed an now it's gone :D

**Comment by MelanX** [comment]
I'm finished :) you could merge and upload an update :D

**Comment by MelanX** [comment]
I was bored so I made Curios optional :D 
Now it's finally ready.

**Comment by DenisMasterHerobrine** [comment]
Thanks for doing great work! :) I really appreciate PRs. I'll make a pre-release (1.1.0-pre1) version, since there is some comments about this Curios compatibility and players want to use Angel Ring as Curios item. I'll make a full 1.1.0 release after fixing mod incompatibility with flying in the game and adding some additions, that I planned months ago.

**Pull request merged**
