### PR TITLE
Created italian translation

### PR DESCRIPTION
**Pull request by maicol07**

### CODE REVIEW

**Comment by DenisMasterHerobrine** [comment]
Thank you for your translation. It will be merged into 2.x version of the mod after some time.

**Comment by DenisMasterHerobrine** [comment]
@maicol07 Mentioning you in case you wondered about this PR. I have updated the mod with lots of new stuff, feel free to update this PR, so I could add the translation into the mod. New .lang file can be found in "1.18.2-2.x" or master branches.

**Comment by maicol07** [comment]
@DenisMasterHerobrine I've updated the translation with the new strings

**Comment by DenisMasterHerobrine** [comment]
Thank you for contribution, I'll commit this next update. 👍

**Pull request merged**
